### ISSUE TITLE
Implement Byzantine behaviour for a validator in the Mysticeti testbed

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/starfish#2]
The Byzantine behavior for a validator includes the following:

- [x] iotaledger/iota-mysticeti#7
  - When the validator is a leader in the scheduler, after some timeout create multiple leader blocks and send those to different nodes.
   - When the validator is not a leader in the scheduler, after some timeout try reference blocks that are not voting for the leader or do not become certificates for the past leaders. Also, create multiple blocks and send those to different nodes.
 - [x] iotaledger/iota-mysticeti#6
   - Byzantine nodes should know each other (they have indices from 1 to f). They create blocks referencing each other and not revealing their blocks to correct nodes for a while (say during f rounds). Then they send their blocks to a leader of the round, which references a batch of blocks not known to other correct nodes. This leader block might then get skipped.
- [x] iotaledger/iota-mysticeti#11
   - When the validator is a leader in the scheduler, simply don't create a block for that round.
- [x] Make unit tests ensuring that leader blocks are not committed 
- [ ] Include a strategy as a parameter for when starting a validator
- [x] Make simulations to identify which strategy decrease the delay most
