### ISSUE TITLE
[Task (consensus-tf)] Proofread Cordial miners and Mysticeti papers

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/starfish#57]
While the safety proofs of both protocols are correct, there seems to be a flaw with proofs of liveness properties.
```[tasklist]
### Tasks
- [x] Check whether there is a flaw (if any)
- [x] Find a way to fix the proof if the flaw is found
- [x] Check whether the timeout conditions/advancing rounds can be modified to improve the resulting latency
```
